name: Build woregnets

on: [ push ]

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: |
          docker build . --file .github/Dockerfile --tag "ghcr.io/${{ github.repository_owner }}/build:${GITHUB_RUN_ID}" --label "runnumber=${GITHUB_RUN_ID}"
      - name: Tag image to main on main branch
        if: ${{github.ref_name == 'main'}}
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/build:${GITHUB_RUN_ID} ghcr.io/${{ github.repository_owner }}/main:${{ github.sha }}
      - name: Log in to docker repo
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push build image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/build:${GITHUB_RUN_ID}
      - name: Push main image
        if: ${{github.ref_name == 'main'}}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/main:${{ github.sha }}
  test:
    runs-on: ubuntu-latest
    needs:
      - build-container
    container:
      image: ghcr.io/${{ github.repository_owner }}/build:${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
      - name: Install requirements
        run: |
          make venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          source venv/bin/activate
          make test
