name: Package maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
      
jobs: 
  remove-packages:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    steps:
      - name: Remove old packages
        uses: actions/delete-package-versions@v5
        with: 
          package-type: container
          package-name: build
          min-versions-to-keep: 0
          