name: Refresh artifact

on:
  workflow_dispatch:

jobs:
  lookup-container-version:
    runs-on: ubuntu-latest
    outputs: 
      sha: ${{ steps.main_sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: main
      - name: Lookup main sha
        id: main_sha
        run: |
          echo "sha=$(git log -1 --format=%H)" >> "$GITHUB_OUTPUT"
  create-artifact:
    runs-on: ubuntu-latest
    needs: lookup-container-version
    container:
      image: ghcr.io/woregnets/main:${{ needs.lookup-container-version.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Build artifact package
        run: |
          make venv
          source venv/bin/activate
          pip install -r requirements.txt
          make build/dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gh-page
          path: 'build/dist/'
