name: Refresh artifact

on:
  workflow_dispatch:
  schedule:
    - cron: "3/5 * * * *"

jobs:
  lookup-container-version:
    runs-on: ubuntu-latest
    outputs: 
      sha: ${{ steps.main_sha.outputs.sha }}
      date: ${{ steps.main_sha.outputs.date }}
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: main
      - name: Lookup main sha
        id: main_sha
        run: |
          echo "sha=$(git log -1 --format=%H)" >> "$GITHUB_OUTPUT"
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
  create-artifact:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    needs: lookup-container-version
    container:
      image: ghcr.io/woregnets/main:${{ needs.lookup-container-version.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache tiles
        uses: actions/cache@v4
        with:
          key: tiles
          path: 'build/tiles'
      - name: Cache dwd data
        uses: actions/cache@v4
        with:
          key: dwd-${{ needs.lookup-container-version.outputs.date }}
          path: |
            build/dwd
            build/radar_images
      - name: Build artifact package
        run: |
          source /opt/python/bin/activate
          make build/dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/dist/'
  deploy:
    runs-on: ubuntu-latest
    needs: create-artifact
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4